services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: indie-clock-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GITHUB_APP_CLIENT_ID=${GITHUB_APP_CLIENT_ID}
      - GITHUB_APP_CLIENT_SECRET=${GITHUB_APP_CLIENT_SECRET}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_ADMIN_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_ADMIN_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_API=http://rabbitmq:15672/api
      - RABBITMQ_ADMIN_USER=${RABBITMQ_ADMIN_USER}
      - RABBITMQ_ADMIN_PASS=${RABBITMQ_ADMIN_PASSWORD}
      - MQTT_URL=mqtt://rabbitmq:1883
      - MQTT_USERNAME=${RABBITMQ_BACKEND_USER}
      - MQTT_PASSWORD=${RABBITMQ_BACKEND_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: ["sh", "-c", "npx prisma migrate deploy && node server.js"]

    networks:
      - indie-clock-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: indie-clock-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - indie-clock-network

  # RabbitMQ with Management Plugin and MQTT Support
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: indie-clock-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_ADMIN_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_ADMIN_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      # Specify writable path for enabled plugins file to avoid permission issues
      RABBITMQ_ENABLED_PLUGINS_FILE: /var/lib/rabbitmq/enabled_plugins.conf
      # List of plugins to enable (management is already enabled in this image, but keep explicit)
      # Enable plugins via environment variable
      RABBITMQ_ENABLED_PLUGINS: "rabbitmq_management,rabbitmq_management_agent,rabbitmq_mqtt"
      # RabbitMQ configuration environment variables
      RABBITMQ_ADMIN_USER: ${RABBITMQ_ADMIN_USER}
      RABBITMQ_ADMIN_PASSWORD: ${RABBITMQ_ADMIN_PASSWORD}
      RABBITMQ_BACKEND_USER: ${RABBITMQ_BACKEND_USER}
      RABBITMQ_BACKEND_PASSWORD: ${RABBITMQ_BACKEND_PASSWORD}
      # MQTT configuration
      RABBITMQ_MQTT_LISTENERS_TCP_DEFAULT: 1883
      RABBITMQ_MQTT_ALLOW_ANONYMOUS: false
      RABBITMQ_MQTT_DEFAULT_USER: ${RABBITMQ_BACKEND_USER}
      RABBITMQ_MQTT_DEFAULT_PASS: ${RABBITMQ_BACKEND_PASSWORD}
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
      - "1883:1883"   # MQTT port (RabbitMQ MQTT plugin)
      - "8883:8883"   # MQTT over SSL
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - indie-clock-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  indie-clock-network:
    driver: bridge
