services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: indie-clock-postgres
    env_file:
      - .env.local
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - indie-clock-network

  # RabbitMQ with Management Plugin and MQTT Support
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: indie-clock-rabbitmq
    env_file:
      - .env.local
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_ADMIN_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_ADMIN_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      # Plugin setup
      RABBITMQ_ENABLED_PLUGINS: "rabbitmq_management,rabbitmq_management_agent,rabbitmq_mqtt"
      RABBITMQ_ENABLED_PLUGINS_FILE: /var/lib/rabbitmq/enabled_plugins.conf
      # MQTT configuration
      RABBITMQ_MQTT_LISTENERS_TCP_DEFAULT: 1883
      RABBITMQ_MQTT_ALLOW_ANONYMOUS: false
    ports:
      - "1883:1883"   # MQTT over SSL port (RabbitMQ MQTT plugin)
      - "15672:15672" # RabbitMQ Management interface
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - indie-clock-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  indie-clock-network:
    driver: bridge 